import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "../assets/css/fonts.css";
import "../assets/css/reset.css";
import "../assets/css/style.css";

import "./globals.css";
import Nav from "../components/Nav";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
	return (
		<html lang="ko">
			<body className={inter.className}>
				<Nav />
				{children}
				<Footer />
			</body>
		</html>
	);
}
